#!/usr/bin/env perl 

use strict;
use warnings;
use 5.014;

use Getopt::Long;
use File::Spec;
use FindBin;

use lib $FindBin::Bin;
use Cens;

GetOptions(
    'dni=s'  => \(my $DNI = ""),
    'data=s' => \(my $DATA = ""),
    'cp=s'   => \(my $CP = ""),
    'help|h' => \(my $HELP),
    'db=s'   => \(my $DB = "./db"),
);

if($HELP) {
    say "Usage $0: --dni 00000000R --data YYYY-MM-DD --cp 08080";
    exit 1;
}

my $cens = Cens->new( db => $DB )
    or exit 1;

$DNI = uc($DNI);
$DNI =~ s#[^0-9A-Z]##g;
unless( $DNI =~ m#^[0-9]{8}[A-Z]$# ) {
    say "El DNI ha de ser en format 00000000R";
    exit 1;
}

$DATA =~ s#[^0-9]##g;
unless( $DATA =~ m#^[0-9]{8}$# ) {
    say "La data de naixement ha de ser en format YYYY-MM-DD";
    exit 1;
}

$CP =~ s#[^0-9]##g;
unless( $CP =~ m#^[0-9]{5}$# ) {
    say "El codi postal has de ser en format 00000";
    exit 1;
}


my $entrada = $cens->cerca( $DNI, $DATA, $CP );

unless( $entrada ) {
    say "No s'ha trobat cap registre a la base de dades";
    exit 1;
}

say <<"EOF"
Adreça:
    $entrada->{adreca1}
    $entrada->{adreca2}

Població:  $entrada->{poblacio}
Districte: $entrada->{districte}

Secció: $entrada->{seccio}
Mesa:   $entrada->{mesa}

HM: $entrada->{hmmm}
EOF

